{{- if .Values.s3Credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendar-assistent.fullname" . }}-s3-credentials
  labels:
    {{- include "calendar-assistent.labels" . | nindent 4 }}
type: Opaque
data:
  s3-credentials.json: {{ .Values.s3Credentials | b64enc }}
{{- end }}
