{{- if .Values.smtpCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendar-assistent.fullname" . }}-smtp-credentials
  labels:
    {{- include "calendar-assistent.labels" . | nindent 4 }}
type: Opaque
data:
  smtp-credentials.json: {{ .Values.smtpCredentials | b64enc }}
{{- end }}
