{{- if .Values.googleCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendar-assistent.fullname" . }}-google-credentials
  labels:
    {{- include "calendar-assistent.labels" . | nindent 4 }}
type: Opaque
data:
  google-credentials.json: {{ .Values.googleCredentials | b64enc }}
{{- end }}
